
[world]
name = "StarkLudo"
description = "Ludo game on Starknet"
cover_uri = "https://imgur.com/inrCls0"
icon_uri = "https://imgur.com/qJINYOd"
website = "https://starkludo.com/"
seed = "starkludo"

[world.socials]
x = "https://x.com/LudoOnStarknet"
discord = ""
github = "https://github.com/sivicstudio/starkludo"
telegram = "https://t.me/+hnjQooODZOA2M2Rk"

[namespace]
default = "starkludo"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x4e4a8cb96198772361acc30c71d81768bccc6c29501f211b0f0ca7045b194a4"
